options:
  preview: "{{ site.frontendUrl }}"

tabs:
  dashboard:
    label: Dashboard
    icon: dashboard
    columns:
      - width: 1/2
        sections:
          pages:
            label: Seiten
            type: pages
            layout: list
            sortable: false
            image:
              cover: true
            create:
              - default
              - simple
            templates:
              - home
              - default
              - simple

      - width: 1/2
        sections:
          choirs: sections/choirs
          notes: sections/notes
  menu:
    label: Navigation
    icon: menu
    fields:
      nav:
        label: Navigation
        type: pages
  global:
    label: Global
    icon: globe
    fields:
      contacts:
        label: "Kontakte"
        type: structure
        fields:
          title:
            label: Titel
            type: text
          contact:
            label: "Ansprechpartner:in"
            type: users
            multiple: false
  media:
    label: Medien
    icon: file
    sections:
      files:
        label: Dateien
        layout: cards